import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import crypto from 'crypto';

const root = process.cwd();
const envPath = path.join(root, '.env');

const sessionSecret = crypto.randomBytes(32).toString('hex');

const envContent = `# Auto-generated by npm run setup — local dev, no external accounts needed
PORT=3001
NODE_ENV=development
CLIENT_URL=http://localhost:5173

# Demo mode: SQLite database + sample creators (no Neon or Google required)
DEV_MODE=true
DATABASE_URL=sqlite:./data/dev.db

# Add real Google OAuth when ready (see README)
GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-client-secret
GOOGLE_REDIRECT_URI=http://localhost:3001/api/auth/google/callback

SESSION_SECRET=${sessionSecret}
`;

if (!fs.existsSync(envPath)) {
  fs.writeFileSync(envPath, envContent);
  console.log('Created .env with demo mode enabled.');
} else {
  console.log('.env already exists — skipped.');
}

console.log('Running database migration…');
execSync('node server/db/migrate.js', { stdio: 'inherit', cwd: root });

console.log('\nSetup complete! Run: npm run dev');
console.log('Then open http://localhost:5173 and click "Try demo — no Google needed".\n');
